#pragma once

#include <deal.II/particles/particle_handler.h>

#include <meltpooldg/time_integration/solution_history.hpp>


namespace MeltPoolDG
{
  /**
   * Spatial dimension of an axial quantity in a dim-dimensional space. This can be used, for
   * example, as the size of torque, angular velocity, or other axial/pseudo-vector quantities.
   *
   * @note dim = 1 is allowed for compatibility or generic code, although from a physical
   * perspective it does not make sense.
   */
  template <int dim>
  inline constexpr int axial_dim = [] {
    if constexpr (dim == 3)
      return 3;
    else
      return 1;
  }();

  /**
   * Computes the torque generated by a force applied at a given position.
   * Given a force vector @p force and a position vector @p distance_to_center_of_gravity
   * pointing from the center of gravity to the point of application, this function returns
   * the resulting torque.
   *
   * - In 3D, the torque is computed using the standard vector cross product:
   *   \f$ \mathbf{M} = \mathbf{r} \times \mathbf{F} \f$.
   * - In 2D, the torque reduces to its scalar z-component:
   *   \f$ M = r_x F_y - r_y F_x \f$.
   *
   * The return type is a Tensor of dimension:
   * - 1D scalar torque (dim = 2 -> Tensor<1,1>)
   * - 3D torque vector (dim = 3 -> Tensor<1,3>)
   *
   * @param force   The applied force vector.
   * @param lever_arm  Vector from center of gravity to point of application.
   *
   * @return The resulting torque as a Tensor.
   */
  template <int dim, typename number>
  dealii::Tensor<1, axial_dim<dim>, number>
  compute_torque(const dealii::Tensor<1, dim, number> &force,
                 const dealii::Tensor<1, dim, number> &lever_arm)
  {
    dealii::Tensor<1, axial_dim<dim>, number> torque;
    if constexpr (dim == 2)
      torque[0] = lever_arm[0] * force[1] - lever_arm[1] * force[0];
    if constexpr (dim == 3)
      torque = dealii::cross_product_3d(lever_arm, force);
    return torque;
  }

} // namespace MeltPoolDG