#pragma once

#include <deal.II/particles/particle_handler.h>

#include <meltpooldg/time_integration/solution_history.hpp>

#include <functional>
#include <vector>


namespace MeltPoolDG
{
  /**
   * Spatial dimension of an axial quantity in a dim-dimensional space. This can be used, for
   * example, as the size of torque, angular velocity, or other axial/pseudo-vector quantities.
   *
   * @note dim = 1 is allowed for compatibility or generic code, although from a physical
   * perspective it does not make sense.
   */
  template <int dim>
  inline constexpr int axial_dim = [] {
    if constexpr (dim == 3)
      return 3;
    else
      return 1;
  }();

  /**
   * Computes the torque generated by a force applied at a given position.
   * Given a force vector @p force and a position vector @p distance_to_center_of_gravity
   * pointing from the center of gravity to the point of application, this function returns
   * the resulting torque.
   *
   * - In 3D, the torque is computed using the standard vector cross product:
   *   \f$ \mathbf{M} = \mathbf{r} \times \mathbf{F} \f$.
   * - In 2D, the torque reduces to its scalar z-component:
   *   \f$ M = r_x F_y - r_y F_x \f$.
   *
   * The return type is a Tensor of dimension:
   * - 1D scalar torque (dim = 2 -> Tensor<1,1>)
   * - 3D torque vector (dim = 3 -> Tensor<1,3>)
   *
   * @param force   The applied force vector.
   * @param lever_arm  Vector from center of gravity to point of application.
   *
   * @return The resulting torque as a Tensor.
   */
  template <int dim, typename number>
  dealii::Tensor<1, axial_dim<dim>, number>
  compute_torque(const dealii::Tensor<1, dim, number> &force,
                 const dealii::Tensor<1, dim, number> &lever_arm)
  {
    dealii::Tensor<1, axial_dim<dim>, number> torque;
    if constexpr (dim == 2)
      torque[0] = lever_arm[0] * force[1] - lever_arm[1] * force[0];
    if constexpr (dim == 3)
      torque = dealii::cross_product_3d(lever_arm, force);
    return torque;
  }

  /**
   * @brief A vector-like view into a specific property of all particles managed by a
   * dealii::Particles::ParticleHandler.
   *
   * This class provides a lightweight interface that mimics the most important features of a
   * deal.II distributed vector, but without owning any memory. Instead, it offers direct access
   * to a selected property (or coordinate component) of each particle managed by the associated
   * ParticleHandler. Conceptually, it exposes that property as if all values were stored in a
   * single, contiguous vector.
   *
   * The main purpose of this class is to enable vector-style operations (such as scaling,
   * addition, or subtraction) directly on particle properties while maintaining compatibility
   * with common deal.II vector interfaces.
   *
   * @note The particle properties are **not stored contiguously in memory**. Each particle stores
   * all of its properties consecutively, and the next particle’s properties follow. Consequently,
   * accessing a specific property across all particles involves a strided memory access pattern.
   */
  template <int dim, typename number>
  class ParticleHandlerVectorView
  {
  public:
    /**
     * @brief Constructor. Initializes the vector view for a specific property of the particles,
     * i.e., sets all required references.
     *
     * @param particle_handler The particle handler that provides access to the actual particle data.
     * @param property_index Index of the property in the particle property array that this vector
     * view should access. If @p index_describes_location is true, this corresponds to the coordinate
     * component (e.g., x/y/z) and must be less than @p dim. In this case it is assumed that the given
     * index corresponds to the spatial direction.
     * @param index_describes_location Flag indicating whether @p property_index refers to a particle
     * location component (true) or a generic property (false).
     */
    ParticleHandlerVectorView(dealii::Particles::ParticleHandler<dim> &particle_handler,
                              unsigned                                 property_index,
                              bool index_describes_location = false);

    /**
     * @brief Scales all elements of the vector view by a given factor.
     *
     * @param factor Scalar multiplier.
     * @return Reference to this vector view.
     */
    ParticleHandlerVectorView<dim, number> &
    operator*=(const number factor);

    /**
     * @brief Divides all elements of the vector view by a given factor.
     *
     * @param factor Scalar divisor.
     * @return Reference to this vector view.
     */
    ParticleHandlerVectorView<dim, number> &
    operator/=(const number factor);

    /**
     * @brief Subtracts another vector view from this one.
     *
     * @param v The vector view to subtract.
     * @return Reference to this vector view.
     */
    ParticleHandlerVectorView<dim, number> &
    operator-=(const ParticleHandlerVectorView<dim, number> &v);


    /**
     * @brief Adds another vector view to this one.
     *
     * @param v The vector view to add.
     * @return Reference to this vector view.
     */
    ParticleHandlerVectorView<dim, number> &
    operator+=(const ParticleHandlerVectorView<dim, number> &v);

    /**
     * This function is only available to make the interface consistent with deal.II vectors. It
     * always returns true.
     */
    bool
    has_ghost_elements() const;

    /**
     * This function is only available to make the interface consistent with deal.II vectors. Since
     * the particle handler does not define ghost element zeroing, this function does nothing.
     */
    void
    zero_out_ghost_elements() const;

    /**
     * @brief Updates ghost particle values.
     *
     * Synchronizes ghost particles across MPI ranks. If @p exchange_particles is true,
     * particles are also exchanged between ranks as needed, potentially changing ownership.
     * In all cases, the properties of ghost particles are updated.
     *
     * @param exchange_particles Whether to exchange ghost particles (true) or only update
     * their properties (false).
     */
    void
    update_ghost_values(const bool exchange_particles = true) const;

    /**
     * @brief Adds a scaled version of another vector view to this one.
     *
     * @param a Scaling factor for the input vector @p v.
     * @param v The vector view to be scaled and added.
     */
    void
    add(const number a, const ParticleHandlerVectorView<dim, number> &v);


    /**
     * @brief Scales this vector and adds a scaled version of another vector.
     *
     * @param s Scaling factor for this vector.
     * @param a Scaling factor for @p v.
     * @param v The vector view to combine with this one.
     */
    void
    sadd(const number s, const number a, const ParticleHandlerVectorView<dim, number> &v);

    /**
     * @brief Returns the number of particles owned by the current MPI process.
     *
     * @return Number of locally owned particles.
     */
    unsigned
    locally_owned_size() const;

    /**
     * @brief Returns a mutable reference to a local particle property.
     *
     * @param index Index of the local particle.
     * @return Mutable reference to the property value.
     */
    number &
    local_element(unsigned index);

    /**
     * @brief Returns the total number of particles in the simulation (global size).
     *
     * @return Global number of particles.
     */
    const number &
    local_element(unsigned index) const;

    /**
     * Returns the size of the vector view, which is effectively the number of global particles.
     */
    unsigned
    size() const;

  private:
    /// The particle handler that provides access to the actual particle data.
    dealii::Particles::ParticleHandler<dim> &particle_handler;

    /// The property index in the particle property array to which this vector view provides
    /// access.
    const unsigned property_index;

    /// Boolean indicating whether the provided property index describes a location (true) or a
    /// property (false). If it is a location, the property index must be less than dim.
    const bool index_describes_location;
  };


  /**
   * @brief A block vector view providing access to multiple particle properties
   * managed by a dealii::Particles::ParticleHandler.
   *
   * This class acts as a lightweight, non-owning container of several
   * ParticleHandlerVectorView objects, each representing a specific particle
   * property or coordinate component. Together, they form a block-structured
   * vector interface similar to deal.II’s BlockVector classes.
   *
   * The block vector view provides a subset of the deal.II block vector interface
   * (e.g., access to blocks, scaling, and addition operations), allowing users
   * to work with multiple particle properties in a unified way while maintaining
   * consistency with deal.II’s vector abstractions.
   *
   * @note Like ParticleHandlerVectorView, this class provides only a view into
   * existing particle data and does not own or allocate any memory. The underlying
   * particle properties are stored in a strided memory layout.
   */
  template <int dim, typename number>
  class ParticleHandlerBlockVectorView
  {
  public:
    /**
     * @brief Default constructor.
     *
     * Constructs an empty block vector view. This constructor does not
     * reference any particle data until one of the @p reinit() functions
     * is called.
     */
    ParticleHandlerBlockVectorView() = default;

    /**
     * @brief Reinitialize the block vector view for particle locations.
     *
     * Initializes the block vector view to provide access to the coordinate
     * components (x, y, z, etc.) of all particles managed by the given
     * ParticleHandler.
     *
     * @param particle_handler Reference to the particle handler that provides
     * access to the particle data.
     */
    void
    reinit(dealii::Particles::ParticleHandler<dim> &particle_handler);

    /**
     * @brief Reinitialize the block vector view for a specific set of particle
     * properties.
     *
     * Sets up one block per entry in @p property_indices, where each block provides
     * access to the corresponding particle property.
     *
     * @param particle_handler Reference to the particle handler managing the
     * particle data.
     * @param property_indices Vector of property indices identifying the properties
     * to be exposed as individual blocks.
     */
    void
    reinit(dealii::Particles::ParticleHandler<dim> &particle_handler,
           const std::vector<unsigned>             &property_indices);

    /**
     * @brief Reinitialize the block vector view for a contiguous range of particle
     * properties.
     *
     * Creates a set of blocks corresponding to a contiguous subset of particle properties.
     * The first property index is given by @p property_indices_begin, and the number of
     * consecutive properties to include is specified by @p property_indices_size.
     *
     * @param particle_handler Reference to the particle handler managing the particle data.
     * @param property_indices_begin Index of the first property in the range.
     * @param property_indices_size Number of consecutive properties to include .
     */
    void
    reinit(dealii::Particles::ParticleHandler<dim> &particle_handler,
           unsigned                                 property_indices_begin,
           unsigned                                 property_indices_size = 1);

    /**
     * Calls the corresponding function on all component views. Only returns true if all component
     * views return true, otherwise it returns false.
     */
    bool
    has_ghost_elements() const;

    /**
     * Calls the corresponding function on all component views.
     */
    void
    zero_out_ghost_elements() const;

    /**
     * @brief Updates ghost particle values across MPI ranks.
     *
     * Synchronizes ghost particles in all component views of this block vector.
     * If @p exchange_particles is true, particle ownership is also updated via MPI
     * exchange as necessary. In all cases, ghost particle properties are refreshed.
     *
     * @param exchange_particles Whether to exchange ghost particles (true)
     * or only update their properties (false). Default is true.
     */
    void
    update_ghost_values(const bool exchange_particles = true) const;

    /**
     * @brief Adds a scaled version of another block vector view to this one.
     *
     * Performs: @code this = this + a * v; @endcode where the operation is applied to all blocks
     * component-wise.
     *
     * @param a Scaling factor for the input block vector @p v.
     * @param v The block vector view to be scaled and added.
     */
    void
    add(const number a, const ParticleHandlerBlockVectorView<dim, number> &v);

    /**
     * @brief Scales this block vector and adds a scaled version of another block vector.
     *
     * Performs: @code this = s * this + a * v; @endcode for each block in the block vector view.
     *
     * @param s Scaling factor for this block vector.
     * @param a Scaling factor for the input block vector @p v.
     * @param v The block vector view to combine with this one.
     */
    void
    sadd(const number s, const number a, const ParticleHandlerBlockVectorView<dim, number> &v);

    /**
     * @brief Returns the number of blocks in this block vector view.
     *
     * Each block corresponds to one particle property or coordinate component.
     */
    unsigned
    n_blocks() const;

    /**
     * @brief Returns a read-only reference to the i-th block vector view.
     *
     * @param i Index of the block to access.
     */
    const ParticleHandlerVectorView<dim, number> &
    block(const unsigned i) const;

    /**
     * @brief Returns a mutable reference to the i-th block vector view.
     *
     * @param i Index of the block to access.
     */
    ParticleHandlerVectorView<dim, number> &
    block(const unsigned i);

  private:
    /// Collection of vector views representing individual particle properties.
    std::vector<ParticleHandlerVectorView<dim, number>> vectors;
  };


  /**
   * @brief Holds required block vector views for DEM particle time integration.
   *
   * This struct groups several @ref ParticleHandlerBlockVectorView objects, each wrapped
   * in a @ref TimeIntegration::SolutionHistory to represent particle quantities such as
   * position, velocity, and acceleration over time.
   *
   * The views provide convenient non-owning access to particle data managed by a
   * @ref dealii::Particles::ParticleHandler, enabling vector-style operations without
   * duplicating storage.
   */
  template <int dim, typename number, typename ObstacleType>
  struct DemTimeIntegratorVectorViews
  {
    /**
     * @brief Constructor.
     *
     * Initializes all time-integration vector views for the given particle handler.
     * Each solution field (location, translational velocity, translational acceleration,
     * angular velocity, and angular acceleration) is reinitialized to provide direct
     * access to the corresponding particle properties defined by @p ObstacleType.
     *
     * @param particle_handler Reference to the particle handlers for different pints in
     * time managing all particle data.
     * @param solution_history_size Number of time levels to allocate in each
     * TimeIntegration::SolutionHistory container.
     */
    DemTimeIntegratorVectorViews(
      const std::vector<std::reference_wrapper<dealii::Particles::ParticleHandler<dim>>>
                    &particle_handlers,
      const unsigned solution_history_size)
      : location(solution_history_size)
      , translational_velocity(solution_history_size)
      , translational_acceleration(solution_history_size)
      , angular_velocity(solution_history_size)
      , angular_acceleration(solution_history_size)
    {
      Assert(solution_history_size == particle_handlers.size(),
             dealii::ExcMessage(
               "The solution history size and the number of particle handlers must match!"));

      for (unsigned i = 0; i < solution_history_size; ++i)
        {
          location.get_solution(i).reinit(particle_handlers[i]);
          translational_velocity.get_solution(i).reinit(particle_handlers[i],
                                                        ObstacleType::Properties::velocity,
                                                        dim);
          translational_acceleration.get_solution(i).reinit(particle_handlers[i],
                                                            ObstacleType::Properties::acceleration,
                                                            dim);
          angular_velocity.get_solution(i).reinit(particle_handlers[i],
                                                  ObstacleType::Properties::angular_velocity,
                                                  ObstacleType::size_angular_velocity);
          angular_acceleration.get_solution(i).reinit(
            particle_handlers[i],
            ObstacleType::Properties::angular_acceleration,
            ObstacleType::size_angular_velocity);
        }
    }

    /// Block vector views for the x/y/z components of particle positions.
    TimeIntegration::SolutionHistory<ParticleHandlerBlockVectorView<dim, number>> location;

    /// Block vector views for the x/y/z components of particle translational velocities.
    TimeIntegration::SolutionHistory<ParticleHandlerBlockVectorView<dim, number>>
      translational_velocity;

    /// Block vector views for the x/y/z components of particle translational acceleration.
    TimeIntegration::SolutionHistory<ParticleHandlerBlockVectorView<dim, number>>
      translational_acceleration;

    /// Block vector views for the x/y/z components of particle angular velocities.
    TimeIntegration::SolutionHistory<ParticleHandlerBlockVectorView<dim, number>> angular_velocity;

    /// Block vector views for the x/y/z components of particle angular acceleration.
    TimeIntegration::SolutionHistory<ParticleHandlerBlockVectorView<dim, number>>
      angular_acceleration;
  };

} // namespace MeltPoolDG