#pragma once

#include <deal.II/base/config.h>

#include <deal.II/base/geometry_info.h>
#include <deal.II/base/tensor.h>

#include <deal.II/grid/cell_id.h>
#include <deal.II/grid/tria.h>
#include <deal.II/grid/tria_accessor.h>
#include <deal.II/grid/tria_iterator.h>

#include <deal.II/particles/particle_handler.h>

#include <meltpooldg/utilities/matrix_free_util.hpp>

#include <meltpooldg/utilities/cpp23_functions.h>
#include <mpi.h>

#include <map>
#include <utility>
#include <vector>


namespace MeltPoolDG
{
  /**
   * Spatial dimension of an axial quantity in a dim-dimensional space. This can be used, for
   * example, as the size of torque, angular velocity, or other axial/pseudo-vector quantities.
   *
   * @note dim = 1 is allowed for compatibility or generic code, although from a physical
   * perspective it does not make sense.
   */
  template <int dim>
  inline constexpr int axial_dim = [] {
    if constexpr (dim == 3)
      return 3;
    else
      return 1;
  }();

  /**
   * Computes the torque generated by a force applied at a given position.
   * Given a force vector @p force and a position vector @p distance_to_center_of_gravity
   * pointing from the center of gravity to the point of application, this function returns
   * the resulting torque.
   *
   * - In 3D, the torque is computed using the standard vector cross product:
   *   \f$ \mathbf{M} = \mathbf{r} \times \mathbf{F} \f$.
   * - In 2D, the torque reduces to its scalar z-component:
   *   \f$ M = r_x F_y - r_y F_x \f$.
   *
   * The return type is a Tensor of dimension:
   * - 1D scalar torque (dim = 2 -> Tensor<1,1>)
   * - 3D torque vector (dim = 3 -> Tensor<1,3>)
   *
   * @param force   The applied force vector.
   * @param lever_arm  Vector from center of gravity to point of application.
   *
   * @return The resulting torque as a Tensor.
   */
  template <int dim, typename number>
  dealii::Tensor<1, axial_dim<dim>, number>
  compute_torque(const dealii::Tensor<1, dim, number> &force,
                 const dealii::Tensor<1, dim, number> &lever_arm)
  {
    dealii::Tensor<1, axial_dim<dim>, number> torque;
    if constexpr (dim == 2)
      torque[0] = lever_arm[0] * force[1] - lever_arm[1] * force[0];
    if constexpr (dim == 3)
      torque = dealii::cross_product_3d(lever_arm, force);
    return torque;
  }

  template <int dim>
  struct LevelCellCache
  {
    void
    reinit(const dealii::Triangulation<dim> &tria, int level)
    {
      using TriaIterator = dealii::TriaIterator<dealii::CellAccessor<dim>>;
      std::map<unsigned int, std::vector<TriaIterator>> vertex_to_cells_map;

      for (auto cell : tria.cell_iterators_on_level(level))
        {
          for (unsigned int vertex_index = 0;
               vertex_index < dealii::GeometryInfo<dim>::vertices_per_cell;
               ++vertex_index)
            {
              vertex_to_cells_map[cell->vertex_index(vertex_index)].push_back(cell);
            }
        }

      if (level > 0)
        {
          for (auto cell : tria.cell_iterators_on_level(level - 1))
            {
              if (!cell->has_children())
                {
                  for (unsigned int vertex_index = 0;
                       vertex_index < dealii::GeometryInfo<dim>::vertices_per_cell;
                       ++vertex_index)
                    {
                      vertex_to_cells_map[cell->vertex_index(vertex_index)].push_back(cell);
                    }
                }
            }
        }


      // First we add all face neighbors
      for (auto cell : tria.cell_iterators_on_level(level))
        {
          // First we add all face neighbors
          for (unsigned int vertex_index = 0;
               vertex_index < dealii::GeometryInfo<dim>::vertices_per_cell;
               ++vertex_index)
            {
              for (const auto &neighbor : vertex_to_cells_map[cell->vertex_index(vertex_index)])
                {
                  cell_to_neighbors[cell].insert(neighbor);
                }
            }
        }



      // Compute the global numbers of cells on the specified level
      n_global_cells_on_level = 0;
      for (auto cell : tria.cell_iterators_on_level(level))
        {
          if (cell->is_locally_owned_on_level())
            n_global_cells_on_level += 1;
        }
      n_global_cells_on_level =
        dealii::Utilities::MPI::sum(n_global_cells_on_level, tria.get_mpi_communicator());
    }

    const std::set<dealii::TriaIterator<dealii::CellAccessor<dim>>> &
    get_neighboring_cells(const dealii::TriaIterator<dealii::CellAccessor<dim>> &cell) const
    {
      Assert(cell_to_neighbors.contains(cell),
             dealii::ExcMessage(
               "The neighboring cells for the given cell have not been computed yet."));

      return cell_to_neighbors.find(cell)->second;
    }

    unsigned int
    n_global_cells() const
    {
      return n_global_cells_on_level;
    }

  private:
    std::map<dealii::TriaIterator<dealii::CellAccessor<dim>>,
             std::set<dealii::TriaIterator<dealii::CellAccessor<dim>>>>
      cell_to_neighbors;

    unsigned int n_global_cells_on_level = 0;
  };


  template <int dim>
  class LevelCellCommunicationPattern
  {
  public:
    LevelCellCommunicationPattern(const dealii::Triangulation<dim> &tria);

    /**
     * Build the communication pattern for the given level. This includes determining which cells on
     * the partition level are relevant for the local process and which other processes need to
     * receive data from or send data to the local process based on the adjacency of cells on the
     * partition level. The communication pattern is stored internally in the class and can be
     * accessed via the provided getter functions.
     *
     * @param level The level for which the communication pattern should be built.
     */
    void
    build_pattern(const unsigned int level);

    /**
     * Get a map that assigns to each MPI rank the cell ids of the locally available cells for which
     * the current process needs to send data to the corresponding other rank.
     */
    std::map<unsigned int, std::vector<dealii::CellId>>
    cells_to_send() const;

    /**
     * Get a map that assigns to each MPI rank the cell ids of locally available cells for which
     * the current process needs to receive data from the corresponding other rank.
     */
    std::map<unsigned int, std::vector<dealii::CellId>>
    cells_to_receive() const;

    /**
     * Return the number of processes to which the current process needs to send data.
     */
    unsigned
    n_processes_to_send_to() const
    {
      return rank_to_cells_send.size();
    }

    /**
     * Return the number of processes from which the current process needs to receive data.
     */
    unsigned
    n_processes_to_receive_from() const
    {
      return rank_to_cells_receive.size();
    }

    /**
     * Number of ranks to which data is sent.
     */
    unsigned int
    n_send_ranks() const;

    /**
     * Number of ranks from which data is received.
     */
    unsigned int
    n_receive_ranks() const;

    /**
     * MPI ranks to which data is sent.
     */
    std::vector<unsigned int>
    send_ranks() const;

    /**
     * MPI ranks from which data is received.
     */
    std::vector<unsigned int>
    receive_ranks() const;

  private:
    /**
     * Return the cells on the partition level that contain at least one locally owned active
     * descendant cell. The returned cells may be locally owned, ghost, or artificial cells.
     *
     * @return Cell ids of the relevant cells on the partition level.
     *
     * @note This function assumes that the relevant partition-level cells are available at least as
     * artificial cells on the current MPI rank. This is guaranteed if the triangulation was created
     * with the multigrid hierarchy enabled.
     */
    std::vector<dealii::CellId>
    owned_active_cells_ancestors() const;

    /**
     * Gather the relevant partition-level cells from all MPI ranks.
     *
     * @param local_ancestor_cells Cell ids of the partition-level cells relevant
     * to the current MPI rank.
     *
     * @return A vector containing, for each MPI rank, the corresponding relevant
     * partition-level cell ids.
     */
    std::vector<std::pair<unsigned, std::vector<dealii::CellId>>>
    gather_ancestors(const std::vector<dealii::CellId> &local_ancestor_cells) const;

    /**
     * Return all relevant adjacent cells of a given partition-level cell. Adjacent cells include
     * the cell itself and all cells on the same level sharing at least one vertex with it. A cell
     * is considered relevant if it contains at least one locally owned active descendant cell.
     *
     * @param cell_id Cell id of the partition-level cell whose adjacent relevant cells should be
     * determined.
     *
     * @param owned_active_cell_ancestors Cell ids of the partition-level cells containing locally
     * owned active descendant cells.
     *
     * @return Cell ids of the adjacent relevant cells.
     */
    std::vector<dealii::CellId>
    adjacent_relevant_cells(const dealii::CellId              &cell_id,
                            const std::vector<dealii::CellId> &owned_active_cell_ancestors) const;

    /**
     * For each MPI rank, determine the relevant local cells adjacent to the cells requested by that
     * rank. In this case adjacent cells include the cell itself and all cells on the same level
     * sharing at least one vertex with it.
     *
     * @param requested_cells_by_rank Vector containing, for each MPI rank, the corresponding
     * relevant partition-level cells.
     *
     * @param owned_active_cell_ancestors Cell ids of the partition-level cells containing locally
     * owned active descendant cells.
     *
     * @return A vector whose entries contain an MPI rank together with the
     * corresponding adjacent relevant local cells.
     */
    std::vector<std::pair<unsigned, std::vector<dealii::CellId>>>
    relevant_cells_for_ranks(
      const std::vector<std::pair<unsigned, std::vector<dealii::CellId>>> &requested_cells_by_rank,
      const std::vector<dealii::CellId> &owned_active_cell_ancestors) const;

    /**
     * Exchange relevant cells with other MPI processes. Each process sends the relevant cells
     * adjacent to the requested partition-level cells to the corresponding MPI rank and receives
     * the relevant cells adjacent to the requested partition-level cells from the other MPI ranks
     *
     * @param cells_to_send A vector of pairs with the first element being the MPI rank and the
     * second element being the corresponding relevant cells for which the corresponding MPI process
     * will receive data from the current process.
     *
     * @return A vector of pairs with the first element being the MPI rank and the second element
     * being the corresponding relevant cells for which the current MPI process will receive data
     * from the corresponding MPI process.
     */
    std::vector<std::pair<unsigned, std::vector<dealii::CellId>>>
    exchange_relevant_cells(
      const std::vector<std::pair<unsigned, std::vector<dealii::CellId>>> &cells_to_send) const;

    /**
     * Store the computed send and receive communication pattern.
     */
    void
    store_rank_cell_maps(
      const std::vector<std::pair<unsigned, std::vector<dealii::CellId>>> &data_to_receive,
      const std::vector<std::pair<unsigned, std::vector<dealii::CellId>>> &data_to_send);

    /**
     * Build the MPI communication pattern for the current partition level.
     */
    void
    build_communication_pattern();

    std::map<unsigned int, std::vector<dealii::CellId>> rank_to_cells_send;

    std::map<unsigned int, std::vector<dealii::CellId>> rank_to_cells_receive;

    /// Reference to the triangulation for which the communication pattern is built.
    const dealii::Triangulation<dim> &triangulation;

    /// The cell level on which the communication pattern is built.
    unsigned int partition_level = 0;

    /// MPI communicator for the communication within the communication pattern. This is typically
    /// the same as the one of the triangulation, but it is stored here separately for better
    /// readability.
    const MPI_Comm mpi_communicator;
  };

} // namespace MeltPoolDG
