#!/bin/sh

# perform sanity check for all json-files
for i in $(find applications/ simulations/ tests/ -type f \( -name "*.json" \) ); do 
  python3 scripts/parameters/sanity_check_json.py  --file $i -w -y &
done
