#!/bin/sh

SCRIPT_DIR=$(dirname "$0")

# format json-files
for i in $(find . -type f -name "*.json" ! -name "parameters.schema.json" -not -path "./build*"); do
  python3 $SCRIPT_DIR/format_json.py $i $i &
done

wait
