#!/bin/sh

format_python_files_in_folder() {
  if [ $# -eq 0 ]; then
    echo "No folder or pattern provided for formatting Python files."
    return 1
  fi

  for target in "$@"; do
    if [ -d "$target" ]; then
      find "$target" -type f -name "*.py" | while read -r i; do
        autopep8 --aggressive --exit-code --ignore E501 -i "$i" &
      done
    fi
  done

  wait
}

# format python files
format_python_files_in_folder scripts/ applications/ tests/ mp-*