name: Pull request run of GitHub CI

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened, labeled ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

env:
  COMPILE_JOBS: 4
  PROJECT_NAME: MeltPoolDG-dev
  CTEST_COMMAND: ctest

jobs:
  build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ready to test') }}
    name: Build ${{ matrix.build_type }}-dealii:${{ matrix.dealii_version }}-${{ matrix.adaflo }}
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        build_type: ["Release"]
        dealii_version: ["master"]

    container:
      image: dealii/dealii:${{ matrix.dealii_version }}-jammy
      options: --user root

    steps:
      - uses: actions/checkout@v4
      - name: Determine filters for ctest
        id: test_command
        run: |
          # Save GitHub labels JSON to a variable
          LABELS_JSON='${{ toJson(github.event.pull_request.labels) }}'

          # Extract label names
          LABELS=$(echo "$LABELS_JSON" | grep -o '"name": "[^"]*"' | cut -d':' -f2 | tr -d '"')
          echo "Labels found: $LABELS"

          TEST_FILTER=""
          for LABEL in mp-compressible-flow mp-advec-diff mp-heat-transfer mp-radiative-transfer mp-reinit mp-level-set unit_tests; do
            if echo "$LABELS" | grep -q "$LABEL"; then
              TEST_FILTER="${TEST_FILTER}${LABEL}|"
            fi
          done

          # Remove trailing '|'
          TEST_FILTER=${TEST_FILTER%|}
          # Construct the final CTEST_COMMAND
          if [ -z ${TEST_FILTER} ] ; then
            FINAL_CTEST_COMMAND="${{ env.CTEST_COMMAND }}"
          else
            FINAL_CTEST_COMMAND="${{ env.CTEST_COMMAND }} -R ${TEST_FILTER}"
          fi
          echo "CTest command: $FINAL_CTEST_COMMAND"

          # Save the new command into the environment variable
          echo "CTEST_COMMAND=$FINAL_CTEST_COMMAND" >> $GITHUB_ENV

      - name: Compile adaflo
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'no_adaflo') }}
        run: |
          git clone https://github.com/MeltPoolDG/adaflo.git
          mkdir adaflo-build
          cd adaflo-build
          cmake \
            -D CMAKE_CXX_STANDARD=20 \
            -D BUILD_SHARED_LIBS=ON \
            -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            ../adaflo
          make -j${{ env.COMPILE_JOBS }} adaflo

      - name: Compile MeltPoolDG
        run: |
          mkdir build
          cd build
          cmake \
            -D CMAKE_CXX_STANDARD=20 \
            -D CMAKE_CXX_FLAGS="-Werror" \
            -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -D ADAFLO_LIB=/__w/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}/adaflo-build/ \
            -D ADAFLO_INCLUDE=/__w/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}/adaflo/include/ \
            ..
          make -j${{ env.COMPILE_JOBS }}

      - name: Test
        run: |
          export HWLOC_HIDE_ERRORS=2
          export OMPI_ALLOW_RUN_AS_ROOT=1
          export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
          cd build
          ${{ env.CTEST_COMMAND }} -j${{ env.COMPILE_JOBS }} --output-on-failure -E 'tests_not_robust/'

      - name: Failed test log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: |
            build/tests/**/*output*
            build/tests/**/*stdout*
            build/unit_tests/**/*output*
            build/unit_tests/**/*stdout*

  clean:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ready to test') }}
    runs-on: self-hosted
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Prune Docker system
        run: |
          docker system prune -af
